### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by johnwess** [tcarlsen/atom-htmlhint#23]
[Enter steps to reproduce:]

1. I deleted all contents of a directory I was following as a project and added replaced with new files.
2. Every action I take in newly created index.html causes this error. Saves, edits, etc.

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [htmlhint](https://github.com/tcarlsen/atom-htmlhint) package 1.1.4

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:107

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at module.exports (/packages/htmlhint/lib/config.coffee:6:43)
    at module.exports (/packages/htmlhint/lib/linter.coffee:19:37)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1190511)
    at Emitter.emit (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1191952)
    at TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:505787)
    at later (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:104700)
```

### Commands

```
 22x -6:15.2.0 core:backspace (input.hidden-input)
  4x -4:44.3.0 intentions:highlight (input.hidden-input)
     -4:43.7.0 core:save (input.hidden-input)
  5x -4:28 intentions:highlight (input.hidden-input)
     -4:27.4.0 core:select-all (input.hidden-input)
undefined -4:26.1.0 intentions:highlight (input.hidden-input)
     -4:22.1.0 core:cut (input.hidden-input)
 12x -3:51.3.0 intentions:highlight (input.hidden-input)
     -3:50.5.0 core:paste (input.hidden-input)
  8x -3:28 intentions:highlight (input.hidden-input)
     -3:27.3.0 core:save (input.hidden-input)
     -3:22.4.0 linter:lint (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -0:21.7.0 core:save (input.hidden-input)
     -0:21.6.0 linter:lint (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
  2x -0:11.5.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-ide-base 2.1.1 
atom-ide-debugger-native-gdb 0.7.3 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
busy-signal 2.0.1 
htmlhint 1.1.4 
ide-cpp 0.1.0 
ide-css 0.3.5 
ide-html 0.6.2 
ide-json 0.2.1 
ide-python 1.5.2 
ide-r 0.1.8 
ide-rust 0.22.0-beta.3 
intentions 1.1.5 
kite 0.196.0 
linter 3.1.1 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-gcc 0.9.0 
linter-htmlhint 1.6.3 
linter-rust 1.0.1 
linter-sass-lint 1.9.0 
linter-ui-default 2.1.4 
minimap-pigments 0.2.2 
minimap-plus 4.35.1 
monokai-seti 0.9.0 
nyan-indent 0.9.8 
pigments 0.40.6 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
prettier-atom 0.60.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
smart-html-tags 1.2.5 
```

**Comment by johnwess** [comment]
I am restarting Atom to see if the error persists.

**Comment by johnwess** [comment]
1. Restart Atom --> Error 
2. Uninstall htmlhint, reinstall htmlhint package, restart Atom --> Error 
3. Uninstall htmlhint, restart Atom --> No Error
