### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by CyanBlob** [tcarlsen/atom-htmlhint#4]
[Enter steps to reproduce below:]

1. ... This happened while working on my webpage project. I am unsure of exactly the cause, but it seems to only happen when changing tabs in my project. The bug then renders me unable to change tabs, unless I choose click a file in the left pane (the file explorer pane). After clicking a file there, I am able to continue to change tabs normally.

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [htmlhint](https://github.com/tcarlsen/atom-htmlhint) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At C:\Users\Andrew\.atom\packages\htmlhint\node_modules\atom-message-panel\lib\MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (C:\Users\Andrew\.atom\packages\htmlhint\node_modules\atom-message-panel\lib\MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (C:\Users\Andrew\.atom\packages\htmlhint\node_modules\atom-message-panel\lib\MessagePanelView.js:108:12)
  at C:\Users\Andrew\.atom\packages\htmlhint\lib\linter.coffee:47:14
  at Emitter.module.exports.Emitter.emit (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\src\pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:328:21)
  at tabs-tab.<anonymous> (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:189:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (C:\Users\Andrew\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -6:33.9 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -5:44.3 settings-view:open (atom-text-editor.editor)
  8x -5:34.2 core:backspace (atom-text-editor.editor.mini)
  3x -3:43.7 core:copy (atom-text-editor.editor)
     -1:29.4 core:paste (atom-text-editor.editor)
     -1:27.4 core:delete (atom-text-editor.editor)
     -1:15.8 core:paste (atom-text-editor.editor)
     -1:14.6 core:save (atom-text-editor.editor)
     -0:28.0 core:cut (atom-text-editor.editor)
     -0:26.7 core:move-up (atom-text-editor.editor)
     -0:26.4 editor:newline (atom-text-editor.editor)
     -0:25.4 snippets:next-tab-stop (atom-text-editor.editor)
     -0:25.4 snippets:expand (atom-text-editor.editor)
     -0:25.4 editor:indent (atom-text-editor.editor)
     -0:24.6 core:paste (atom-text-editor.editor)
     -0:23.6 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-atom",
      "remote-sync",
      "remote-edit"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
htmlhint, v1.0.1
language-prolog, v0.9.0
linter, v0.11.1
linter-clang, v2.25.1
linter-htmlhint, v0.0.8

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
this was an error in atom-message-panel in the latest version. It has been fixed but the only way for you to get rid of it is to reinstall htmllint (uninstall/install)

https://github.com/tcarlsen/atom-message-panel/issues/65
