### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by radarsu** [tcarlsen/atom-htmlhint#7]
[Enter steps to reproduce below:]

1. During saving file
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [htmlhint](https://github.com/tcarlsen/atom-htmlhint) package, v1.1.3

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:809

TypeError: Arguments to path.join must be strings
  at f (path.js:190:13)
  at Object.filter (native)
  at Object.win32.join (path.js:195:38)
  at module.exports (C:\Users\Artur\.atom\packages\htmlhint\lib\config.coffee:6:43)
  at module.exports (C:\Users\Artur\.atom\packages\htmlhint\lib\linter.coffee:19:37)
  at Emitter.module.exports.Emitter.emit (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -9:14.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -9:14.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:10.7.0 selector-to-tag:solve-selector (atom-text-editor.editor.is-focused)
     -9:10.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -9:10.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:10.7.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -9:10.7.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -9:10.1.0 core:undo (atom-text-editor.editor.is-focused)
     -9:08.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:52.9.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -0:09.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:09.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:07.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "slack-chat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.12
atom-html-preview, v0.1.11
auto-id-class, v0.2.6
autocomplete-modules, v1.1.0
clipboard-history, v0.6.6
color-picker, v2.0.12
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
docblockr, v0.7.3
docs-snippets, v0.8.0
figletify, v0.1.3
file-icons, v1.6.9
font-viewer, v0.3.0
fonts, v0.6.0
foundation5-snippets, v0.2.2
htmlhint, v1.1.3
js-patterns-atom-snippets, v0.2.1
jshint, v1.8.0
keyboard-localization, v1.4.8
keycodes, v0.1.4
local-server-express, v0.3.1
minimap, v4.13.3
pigments, v0.15.0
Remote-FTP, v0.7.2
selector-to-tag, v0.4.1
seti-icons, v0.4.5
smart-tags, v0.1.0
tag, v0.3.0
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
this could be part of the same issue over at atom-message-panel (https://github.com/tcarlsen/atom-message-panel/issues/77) about linting unsaved files
